name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1
  get_it: ^7.2.0
  google_fonts: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  go_router: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  